apiVersion: v1
kind: Service
metadata:
  name: identity-server-service
spec:
  type: NodePort
  selector:
    app: myidentityserver
  ports:
    - name: myidentityserver
      protocol: TCP
      port: 8080
      targetPort: 8080